# Makefile for baseline RISC-V test
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../rtl/simple_riscv.v
TOPLEVEL = simple_riscv
MODULE = test_baseline

include $(shell cocotb-config --makefiles)/Makefile.sim
